AWSTemplateFormatVersion: 2010-09-09
Description: Application Load Balancer and API Gateway

Resources:
  # Dependancies: ALB, Target Group, Listener
  # Output: target group ARN
  myAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 30
        - Key: routing.http.desync_mitigation_mode
          Value: strictest
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: true
        - Key: routing.http.xff_header_processing.mode
          Value: remove
      Scheme: internal
      SecurityGroups:
        - !ImportValue ALBsecGroup-Id
      Subnets:
        - !ImportValue appSubA-Id
        - !ImportValue appSubB-Id
  
  myAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref myAppTargetGroup
      LoadBalancerArn: !Ref myAppLoadBalancer
      Port: 80
      Protocol: HTTP
      
  myAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount: 3
      IpAddressType: ipv4
      Matcher:
        HttpCode: 200
      Name: car-app-target-group-01
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !ImportValue baseVPC-Id
  
  # API Gateway
  # Dependancies: ALB for private integration, VPC link for API Gateway (creates ENI)

Outputs:

  myAppTargetGroupArn:
    Description: The ARN of the Listener Target Group
    Value: !GetAtt myAppTargetGroup.TargetGroupArn
    Export:
      Name: carAppTargetGroup-Arn