AWSTemplateFormatVersion: 2010-09-09
Description: RDS instance

Parameters:
  MasterUsername:
    Description: "The database admin account username"
    Type: String
    MinLength: 4
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must be 4-16 characters and contain only alphanumeric characters."

  MasterUserPassword:
    Description: "The database admin account password"
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9@]*"
    ConstraintDescription: "Must be 8-41 characters and contain alphanumeric characters or @."

Resources:

  mainDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 2
      DBInstanceClass: db.t4g.micro
      DBInstanceIdentifier: car-project-2025
      DBSubnetGroupName: !Ref myDBsubnets
      DeleteAutomatedBackups: true
      Engine: postgres
      EngineLifecycleSupport: open-source-rds-extended-support-disabled
      EngineVersion: "17.4"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MultiAZ: true
      NetworkType: IPV4
      Port: 5432
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue DBsecGroup-Id

  myDBsubnets:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets used for Multi-AZ DB
      DBSubnetGroupName: myDB-subnet-group
      SubnetIds: 
        - !ImportValue privSubA-Id
        - !ImportValue privSubB-Id
