AWSTemplateFormatVersion: 2010-09-09
Description: RDS instance creation and init

Resources:

  #DBSecret:
    #Type: AWS::SecretsManager::Secret
    #Properties:
      #Name: /rds/postgresql/master
      #Description: RDS PostgreSQL master credentials
      #GenerateSecretString:
        #SecretStringTemplate: '{"username":"master_user"}'
        #GenerateStringKey: password
        #ExcludeCharacters: '"@/\-+$*'
        #PasswordLength: 12

  mainDBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBSecret
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 1
      CACertificateIdentifier: rds-ca-rsa2048-g1
      DBInstanceClass: db.t4g.micro
      DBInstanceIdentifier: car-project-2025
      DBSubnetGroupName: !Ref myDBsubnets
      DeleteAutomatedBackups: true
      EnableIAMDatabaseAuthentication: true
      Engine: postgres
      EngineLifecycleSupport: open-source-rds-extended-support-disabled
      EngineVersion: "17.4"
      #MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}::username}}'
      MasterUsername: master_user
      #MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}::password}}' 
      MasterUserPassword: password123 #hardcoded for cost
      MultiAZ: false #temporarily disabling due to cost
      NetworkType: IPV4
      Port: 5432
      PubliclyAccessible: false
      StorageType: gp2
      StorageEncrypted: true
      VPCSecurityGroups:
        - !ImportValue DBsecGroup-Id

  myDBsubnets:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets used for Multi-AZ DB
      DBSubnetGroupName: myDB-subnet-group
      SubnetIds: 
        - !ImportValue privSubA-Id
        - !ImportValue privSubB-Id

  myLambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: Lambda-exec-role
      MaxSessionDuration: 14400
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies: 
        - PolicyName: SM-and-RDS-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SecretsAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Ref DBSecret
              - Sid: RdsHealthCheck
                Effect: Allow
                Action:
                  - rds:DescribeDBInstances #use to check if DB running
                Resource: !GetAtt mainDBInstance.DBInstanceArn
              - Sid: CloudWatchAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  