AWSTemplateFormatVersion: 2010-09-09
Description: VPC structure
# VPC, public & private subnets, route table, IGW, DB SG, EC2 SG

Parameters:

  LocalIpAddress:
    Description: "The IP CIDR range allowed to SSH into the instance"
    Type: String
    Default: 3.8.37.24/29

Resources:

  baseVPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/20
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: baseVPC

  pubA:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: !Select [0, !GetAZs ""] 
      CidrBlock: 10.10.1.0/24
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: pubSubA
      VpcId: !Ref baseVPC

  pubB:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.10.2.0/24
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: pubSubB
      VpcId: !Ref baseVPC

  privA:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.10.3.0/24
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: privSubA
      VpcId: !Ref baseVPC

  privB:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.10.4.0/24
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: privSubB
      VpcId: !Ref baseVPC

  myInternetGw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name
          Value: Internet Gateway

  IgwAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref myInternetGw
      VpcId: !Ref baseVPC

  pubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name
          Value: publicRouteTable
      VpcId: !Ref baseVPC

  routeToIgw:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref myInternetGw
      RouteTableId: !Ref pubRT

  pubASubAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref pubRT
      SubnetId: !Ref pubA

  pubBSubAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref pubRT
      SubnetId: !Ref pubB
  
  privRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name
          Value: privateRouteTable
      VpcId: !Ref baseVPC

  privASubAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privRT
      SubnetId: !Ref privA

  privBSubAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privRT
      SubnetId: !Ref privB

  DBsecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the Multi-AZ DB
      GroupName: postgres-secGroup
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref EC2secGroup
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
      VpcId: !Ref baseVPC

  EC2secGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instances
      GroupName: ec2-secGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref LocalIpAddress
      VpcId: !Ref baseVPC

Outputs:

  baseVPCId:
    Description: The id of the VPC resource
    Value: !Ref baseVPC
    Export:
      Name: baseVPC-Id
  
  privRTId:
    Description: The id of the RT for private subnets
    Value: !Ref privRT
    Export:
      Name: privRT-Id

  pubAId:
    Description: The id of public subnet A
    Value: !Ref pubA
    Export:
      Name: pubSubA-Id

  pubBId:
    Description: The id of public subnet B
    Value: !Ref pubB
    Export:
      Name: pubSubB-Id

  privAId:
    Description: The id of private subnet A
    Value: !Ref privA
    Export:
      Name: privSubA-Id

  privBId:
    Description: The id of private subnet B
    Value: !Ref privB
    Export:
      Name: privSubB-Id

  DBsecurityGroup:
    Description: Security group for DB
    Value: !Ref DBsecGroup
    Export:
      Name: DBsecGroup-Id
  
  EC2securityGroup:
    Description: Security group for EC2 instances
    Value: !Ref EC2secGroup
    Export:
      Name: EC2secGroup-Id